DROP TABLE IF EXISTS `analyses`;
CREATE TABLE `analyses` (
  `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `uuid` CHAR(36) NOT NULL UNIQUE,
  `user_id` BIGINT UNSIGNED NULL,
  `image_path` VARCHAR(512) NOT NULL,
  `image_original_name` VARCHAR(255) DEFAULT NULL,
  `image_size` INT UNSIGNED DEFAULT NULL,
  `image_mime_type` VARCHAR(100) DEFAULT NULL,
  `thumbnail_path` VARCHAR(512) DEFAULT NULL,
  `doigt_concerne` ENUM('pouce', 'index', 'majeur', 'annulaire', 'auriculaire', 'orteil') DEFAULT NULL,
  `main_pied` ENUM('main_gauche', 'main_droite', 'pied_gauche', 'pied_droit') DEFAULT NULL,
  `result_json` JSON DEFAULT NULL,
  `pathologie_detectee_id` BIGINT UNSIGNED DEFAULT NULL,
  `pathologie_label` VARCHAR(255) DEFAULT NULL,
  `score_confiance` DECIMAL(5,4) DEFAULT NULL,
  `niveau_risque` ENUM('sain', 'bas', 'modere', 'eleve', 'critique') DEFAULT 'bas',
  `recommandation_consultation` TINYINT(1) DEFAULT 0,
  `model_version` VARCHAR(64) DEFAULT NULL,
  `processing_time_ms` INT UNSIGNED DEFAULT NULL,
  `heatmap_path` VARCHAR(512) DEFAULT NULL,
  `segmentation_path` VARCHAR(512) DEFAULT NULL,
  `status` ENUM('pending', 'processing', 'completed', 'failed', 'archived') DEFAULT 'pending',
  `error_message` TEXT DEFAULT NULL,
  `ip_address` VARCHAR(45) DEFAULT NULL,
  `user_agent` VARCHAR(512) DEFAULT NULL,
  `notes_utilisateur` TEXT DEFAULT NULL,
  `date_analyse` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `completed_at` TIMESTAMP NULL,
  INDEX `idx_uuid` (`uuid`),
  INDEX `idx_user_id` (`user_id`),
  INDEX `idx_status` (`status`),
  INDEX `idx_niveau_risque` (`niveau_risque`),
  INDEX `idx_date` (`date_analyse`),
  INDEX `idx_pathologie` (`pathologie_detectee_id`),
  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`pathologie_detectee_id`) REFERENCES `pathologies`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
